name: AI-diagnostic
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.9.21
  - scikit-learn=1.6.1
  - monai=1.4.0
  - numpy=1.26.4
  - pandas
  - pingouin
  - matplotlib
  - seaborn
  - statsmodels
  - tqdm
  - imageio
  - nibabel=5.3.2
  - pydicom
  - pillow
  - jupyter
  - jupyterlab
  - ipython
  - pip
  - tensorboard=2.17.0
  - einops
  - imbalanced-learn
  - tsfresh=0.18.0
  - pip:
    - labelme==5.6.1
    - SimpleITK
    - torch==2.1.2 
    - torchvision==0.16.2 
    - pyradiomics==3.1.0
    - opencv-pythonx
    - huggingface_hub
    - protobuf==3.20.*
